### PR TITLE
Shadow 8.1.1

### PR DESCRIPTION
**Pull request by Goooler**
See https://github.com/johnrengelman/shadow/issues/834#issuecomment-1447441625.

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Closes https://github.com/gradle-nexus/publish-plugin/pull/197

**Review by TWiStErRob — APPROVED** [review]
Did a quick diff of the `gradlew publishToMavenLocal` output, they're the same for both builds.

**Review by szpak — APPROVED** [review]

**Comment by szpak** [comment]
Thanks @Goooler .

**Comment by szpak** [comment]
And thanks @TWiStErRob for the review.

**Pull request merged**
