### PR TITLE
Fix #228: reduce parallelism in task and increase parallelism between tasks

### LINKED ISSUE #228: Failing "IvyNexusPublishPluginTests > can be used with lazily applied Gradle Plugin Development Plugin" on CI with LockTimeoutException
The (compatibility) test "IvyNexusPublishPluginTests > can be used with lazily applied Gradle Plugin Development Plugin" failed twice on CI ([1](https://github.com/gradle-nexus/publish-plugin/actions/runs/5152744338/jobs/9279172923#step:4:216), [2](https://github.com/gradle-nexus/publish-plugin/actions/runs/5152865393/jobs/9280072186#step:4:222)) in short period of time. Both times on Mac and both times in the Ivy version (once with 7.6.1, once with 8.0.2) . The error in the output is not very helpful:

```
IvyNexusPublishPluginTests > can be used with lazily applied Gradle Plugin Development Plugin FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at DefaultGradleRunner.java:269
```

luckily, the [build scan](https://gradle.com/s/kgpvb2h4jwfbi) is more verbose:
```
> Task :initializeSonatypeStagingRepository	
Created staging repository 'orgexample-42' at http://localhost:49978/repositories/orgexample-42/content/	
	
> Task :gradle-plugin:generateDescriptorFileForFooPluginMarkerIvyPublication	
> Task :gradle-plugin:publishFooPluginMarkerIvyPublicationToSonatypeRepository	
> Task :gradle-plugin:generateDescriptorFileForPluginIvyPublication	
> Task :gradle-plugin:compileJava	
> Task :gradle-plugin:compileJava FAILED	
	
FAILURE: Build failed with an exception.	
	
* What went wrong:	
Execution failed for task ':gradle-plugin:compileJava'.	
> Could not resolve all files for configuration ':gradle-plugin:compileClasspath'.	
   > Timeout waiting to lock Generated Gradle JARs cache (/Users/runner/work/publish-plugin/publish-plugin/build/tmp/compatTest7.6.1/work/.gradle-test-kit/caches/7.6.1/generated-gradle-jars). It is currently in use by another Gradle instance.	
     Owner PID: 26887	
     Our PID: 26886	
     Owner Operation: 	
     Our operation: 	
     Lock file: /Users/runner/work/publish-plugin/publish-plugin/build/tmp/compatTest7.6.1/work/.gradle-test-kit/caches/7.6.1/generated-gradle-jars/generated-gradle-jars.lock	
	
* Try:	
> Run with --info or --debug option to get more log output.	
> Run with --scan to get full insights.	
	
* Exception is:	
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gradle-plugin:compileJava'.	
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)	
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
...
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':gradle-plugin:compileClasspath'.
...
Caused by: org.gradle.cache.LockTimeoutException: Timeout waiting to lock Generated Gradle JARs cache (/Users/runner/work/publish-plugin/publish-plugin/build/tmp/compatTest7.6.1/work/.gradle-test-kit/caches/7.6.1/generated-gradle-jars). It is currently in use by another Gradle instance.	
Owner PID: 26887	
Our PID: 26886	
Owner Operation: 	
Our operation: 	
Lock file: /Users/runner/work/publish-plugin/publish-plugin/build/tmp/compatTest7.6.1/work/.gradle-test-kit/caches/7.6.1/generated-gradle-jars/generated-gradle-jars.lock	
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.timeoutException(DefaultFileLockManager.java:344)	
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:305)	
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:164)
```

@maczikasz Do you think it is Ivy specific? Maybe you have any idea how to mitigate it?

### PR DESCRIPTION
**Pull request by TWiStErRob**
Please squash when merging.

Fixes #228 by not running two Gradle tests of the same version.

See [performance impact](https://github.com/gradle-nexus/publish-plugin/issues/228#issuecomment-1634091691) (positive, at least on my machine 😅) in the related issue.

`org.gradle.parallel` parallelizes tasks between projects.
`org.gradle.configuration-cache` parallelizes tasks inside projects.
`maxParallelForks` parallelizes Test classes inside Test tasks.

This PR
* reduces maxParallelForks to 1 so that `compatTestSomeGradleVersion` cannot run two tests which have the same Gradle needs at the same time.
* enables configuration cache so that `compatTestGradle1` and `compatTestGradle2` can run in parallel.
* Migrated from direct task access to newer APIs in KGP to prevent this warning:
```
> Task :compileKotlin
kotlinOptions.freeCompilerArgs were changed on task :compileKotlin execution phase: -java-parameters, -Xjvm-default=all, -Xjsr305=strict, -Xsam-conversions=class, -XXLanguage:+DisableCompatibilityModeForNewInference,
 -XXLanguage:-TypeEnhancementImprovementsInStrictMode, -Xsuppress-version-warnings
This behaviour is deprecated and become an error in future releases!
Approximate place of modification at execution phase:
    Build_gradle$11$1$1$1.execute(build.gradle.kts:179)
    Build_gradle$11$1$1$1.execute(build.gradle.kts:176)
```

Enabling configuration cache has a side effect: this is printed to the console:
```
> Task :compileKotlin
w: ATTENTION!
This build uses unsafe internal compiler arguments:

-XXLanguage:+DisableCompatibilityModeForNewInference
-XXLanguage:-TypeEnhancementImprovementsInStrictMode

This mode is not recommended for production use,
as no stability/compatibility guarantees are given on
compiler or generated code. Use it at your own risk!
```
it looks scary, but there's a [bug](https://github.com/gradle/gradle/issues/25483) in Gradle kotlin-dsl plugin which means that `org.gradle.kotlin.dsl.plugins.dsl.ExperimentalCompilerWarningSilencer` is not in play when CC is used.

### CODE REVIEW

**Comment by TWiStErRob** [comment]
@szpak I see you made 6 attempts on another PR, I think you can merge this first. It should help with all the others.

**Comment by TWiStErRob** [comment]
That said, there's something strange, everything is FROM-CACHE on this PR. But where did the cache get populated?

**Comment by TWiStErRob** [comment]
Ok, looks good now, after random change the effect is visible:
| What? | Last PR | This PR |
| - | - | - |
| CI > gradle (macos-latest) | [scan](https://gradle.com/s/y2q2virpnhx3e/timeline) image image | [scan](https://scans.gradle.com/s/fgh3x6ckcqa2s/timeline) image image |
| Java x-version OpenJDK 11 | [scan](https://gradle.com/s/p7xqbfczbmv34/timeline) image image | [scan](https://scans.gradle.com/s/5vdtc7t74jpqa/timeline) image image |

So this confirms `maxParallelForks = 1` is beneficial even for a single task (probably due to Gradle locking of parallel executions). I think for for CI, the bigger time is because the whole computer is more busy, but because of 3x parallelism it's still 18 -> 7 minutes 😲.

**Review by szpak — APPROVED** [review]

**Comment by szpak** [comment]
Really nice, and more reliable.

**Pull request merged**
