### PR TITLE
Update plugin-publish plugin

### PR DESCRIPTION
**Pull request by turansky**

### CODE REVIEW

**Comment by szpak** [comment]
Thanks @turansky.

@marcphilipp It failed in a strange way, but it is not related to this change. I triggered CI for the latest version and it [also fails](https://github.com/gradle-nexus/publish-plugin/runs/4128156982?check_suite_focus=true#step:5:446) with:
> Caused by: java.lang.ClassNotFoundException: kotlin.jvm.JvmInline

You are closer to Kotlin and Dokka, so maybe you have an idea why?

Btw, it went under the radar as our cron job calls "just" e2e-tests which don't generate docs in the main project.

**Comment by turansky** [comment]
Looks like higher Gradle (with more higher Kotlin) required for plugin

**Comment by szpak** [comment]
> Looks like higher Gradle (with more higher Kotlin) required for plugin

Might be, however, I would expect to see the pipeline failing after that change. Here, "something" changed over time outside the project (minor version of JDK?) which is not expected.

**Comment by marcphilipp** [comment]
I tried with 11.0.10-11.0.13 and it fails with all of them. Not sure why/how this ever worked.

**Comment by marcphilipp** [comment]
https://github.com/gradle-nexus/publish-plugin/pull/124 will remove Dokka from the build and should solve this issue.

**Comment by vlsi** [comment]
The error is

```
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/JvmInline
	at com.fasterxml.jackson.module.kotlin.ExtensionsKt.isUnboxableValueClass(Extensions.kt:122)
	at com.fasterxml.jackson.module.kotlin.KotlinSerializers.findSerializer(KotlinSerializers.kt:69)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:215)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:173)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1495)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1443)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:544)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:822)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4569)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3822)
	at org.jetbrains.dokka.utilities.JsonKt.toJsonString(json.kt:32)
	at org.jetbrains.dokka.ConfigurationKt.toJsonString(configuration.kt:88)
```

It means that `jackson.module.kotlin.ExtensionsKt.isUnboxableValueClass(Extensions.kt:122)` attemps access `JvmInline` annotation (it was introduced in Kotlin 1.5), and Gradle does not allow to reliably upgrade kotlin-stdlib in the buildscript classpath.

That boils down to two solutions:
a) Rely only on plugins that target Kotlin 1.4 (e.g. older versions of Dokka)
b) Add try-catch to jackson.module so it ignores the missing JvmInline feature
c) Try shuffling the order of plugins
d) Allow kotlin-stdlib upgrades in Gradle

**Comment by vlsi** [comment]
By the way, I wonder what triggered jackson.module upgrade.
It would be not really fun if com.gradle.plugin-publish triggers jackson upgrade which effectively breaks builds since the new jackson requires Kotlin 1.5, and Gradle can't deliver it in Gradle 6.9

**Comment by vlsi** [comment]
The offending plugin is 

```
+--- org.ajoberstar.stutter:org.ajoberstar.stutter.gradle.plugin:0.6.0
|    \--- org.ajoberstar:gradle-stutter:0.6.0
|         \--- com.fasterxml.jackson.core:jackson-databind:latest.release -> 2.13.0 (*)
```

So you basically should ask `gradle-stutter` to refrain from upgrading to `jackson` versions that require Kotlin 1.5, or you should refrain from depending on newer `stutter` versions

**Comment by vlsi** [comment]
The problematic JvmInline PR was introduced in 2.13.0: https://github.com/FasterXML/jackson-module-kotlin/pull/468

**Comment by marcphilipp** [comment]
@vlsi Thanks for the root cause analyis! 👍 

@turansky Please rebase this PR on the lastest `master` since #124 has now been merged.

**Pull request merged**
