### PR TITLE
Fix #152: remove usage of ConfigureUtil.configureUsing

### LINKED ISSUE #152: ConfigureUtil deprecation warning
fyi I noticed this in a build scan,

> The org.gradle.util.ConfigureUtil type has been deprecated. 
This is scheduled to be removed in Gradle 9.0.
[Documentation](https://docs.gradle.org/7.6-rc-1/userguide/upgrading_version_7.html#org_gradle_util_reports_deprecations)

https://github.com/gradle-nexus/publish-plugin/blob/0aea95597e2eeaf9275a286254894bad29b3d1e1/src/main/kotlin/io/github/gradlenexus/publishplugin/DefaultNexusRepositoryContainer.kt#L32

### PR DESCRIPTION
**Pull request by TWiStErRob**
Does not cl_ose #152, because there's another instance of ConfigureUtil, but makes progress and provides an immediate win.

### CODE REVIEW

**Review by szpak — APPROVED** [review]

**Comment by szpak** [comment]
Thanks.

**Comment by szpak** [comment]
Ups, the merge queue didn't squash the commits...

**Comment by TWiStErRob** [comment]
Do you want to force push master and re-merge?

**Comment by szpak** [comment]
No, I was just (negatively) surprised :). Force pushing to master in a public project is quite nasty ;).

**Pull request merged**
